[package]
name = "glutin"
version = "0.28.0"
authors = [
  "The glutin contributors",
  "Pierre Krieger <pierre.krieger1708@gmail.com>",
]
description = "Cross-platform OpenGL context provider."
keywords = ["windowing", "opengl"]
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/rust-windowing/glutin"
documentation = "https://docs.rs/glutin"
edition = "2018"

[package.metadata.docs.rs]
features = ["serde"]

[features]
serde = ["winit/serde"]
x11 = ["winit/x11", "glutin_glx_sys"]
wayland = [
  "winit/wayland",
  "winit/wayland-dlopen",
  "wayland-client",
  "wayland-egl",
]
wayland-dlopen = ["winit/wayland-dlopen"]
kms = ["drm", "gbm", "winit/kms"]
default = ["x11", "wayland", "wayland-dlopen", "kms"]

[dependencies]
lazy_static = "1.4.0"
# winit = { version = "0.26", default-features = false }
winit = { git = "https://github.com/StratusFearMe21/winit", default-features = false }

[target.'cfg(target_os = "android")'.dependencies]
android_glue = "0.2.3"
glutin_egl_sys = { version = "0.1.5", path = "../glutin_egl_sys" }
parking_lot = "0.12.0"

[target.'cfg(target_os = "emscripten")'.dependencies]
glutin_emscripten_sys = { version = "0.1.1", path = "../glutin_emscripten_sys" }

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
objc = "0.2.7"
glutin_gles2_sys = { version = "0.1.5", path = "../glutin_gles2_sys" }

[target.'cfg(target_os = "macos")'.dependencies]
cgl = "0.3.2"
cocoa = "0.24.0"
core-foundation = "0.9.3"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.9"
features = ["winnt", "winuser", "wingdi", "libloaderapi"]

[target.'cfg(target_os = "windows")'.dependencies]
libloading = "0.7.3"
glutin_wgl_sys = { version = "0.1.5", path = "../glutin_wgl_sys" }
glutin_egl_sys = { version = "0.1.5", path = "../glutin_egl_sys" }
parking_lot = "0.12.0"

[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "dragonfly", target_os = "netbsd", target_os = "openbsd"))'.dependencies]
osmesa-sys = "0.1.2"
wayland-client = { version = "0.29.4", features = ["dlopen"], optional = true }
wayland-egl = { version = "0.29.4", optional = true }
libloading = "0.7.3"
glutin_egl_sys = { version = "0.1.5", path = "../glutin_egl_sys" }
glutin_glx_sys = { version = "0.1.7", path = "../glutin_glx_sys", optional = true }
parking_lot = "0.12.0"
log = "0.4.17"
drm = { version = "0.6.2", optional = true }
gbm = { version = "0.8.0", optional = true }
